services:
  proxy:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '3000:80'
    depends_on:
      - backend
      - frontend
    networks:
      - erp_network

  backend:
    container_name: fastapi_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: yolo_backend:1.0
    expose:
      - '8000'
    networks:
      - erp_network
    restart: always

  frontend:
    container_name: frontenderp
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: yolo_frontend:1.0
    command: bash -c "cd /frontend && npm install && npm run dev -- --host 0.0.0.0 --port 5000"
    volumes:
      - ./frontend/app:/frontend
    depends_on:
      - backend
    networks:
      - erp_network
    restart: always

networks:
  erp_network:
    driver: bridge
