services:
  frontend:
    container_name: angular_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      erp_network:
        aliases:
          - frontend
    restart: always

  nginx:
    container_name: nginx_proxy
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - erp_network
    depends_on:
      - frontend

networks:
  erp_network:
    driver: bridge
