services:
  backend:
    container_name: fastapi_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: yolo_backend:1.0
    networks:
      - erp_network
    restart: always

  frontend:
    container_name: angular_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: yolo_frontend:1.0
    networks:
      erp_network:
        aliases:
          - frontend
    restart: always

  nginx:
    container_name: nginx_proxy
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      erp_network:
        aliases:
          - backend
          - frontend
    depends_on:
      - backend
      - frontend

networks:
  erp_network:
    driver: bridge
